packages:
  - 'shared'
  - 'apps/*'
  - 'packages/*'

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver

allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  '@tarojs/binding': true
  '@tarojs/cli': true
  core-js: true
  core-js-pure: true
  esbuild: true
  swiper: true
  unrs-resolver: true
