// ═════════════════════════════════════════════════════════════
// Auto-generated by scripts/generate-works.mjs
// Do not edit manually — run `pnpm generate:works` to regenerate
// Generated: 2026-06-11T14:29:55.164Z
// Total files scanned: 20
// Total works: 20
// ═════════════════════════════════════════════════════════════

export interface WorkEntry {
  id: string;
  title: string;
  description: string;
  categoryId: string;
  type: 'video' | 'image';
  file: string;
  thumbnail: string;
  tools: string[];
  tags: string[];
  duration: string;
  createdAt: string;
  featured: boolean;
  bvid?: string;
}

export const WORKS_DATA: WorkEntry[] = [
  {
    "id": "2026马年元宵节-霓虹灯火",
    "title": "2026马年元宵节 · 霓虹灯火",
    "description": "AI 生成的动画风格短片，展现2026年马年元宵节现代都市街头的霓虹灯与红色元宵节灯笼交相辉映的节日氛围。融合传统节日元素与赛博朋克风格的光影效果。",
    "categoryId": "ai-animation-drama",
    "type": "video",
    "file": "ai-animation-drama/2026年马年元宵节，现代都市街头，夜晚的霓虹灯与红色的元宵节灯笼交相辉映.mp4",
    "thumbnail": "ai-animation-drama/2026年马年元宵节，现代都市街头，夜晚的霓虹灯与红色的元宵节灯笼交相辉映.thumb.jpg",
    "tools": [
      "即梦AI",
      "剪映专业版"
    ],
    "tags": [
      "元宵节",
      "AI动画",
      "节日氛围",
      "赛博朋克"
    ],
    "duration": "00:30",
    "createdAt": "2026-02",
    "featured": true
  },
  {
    "id": "马年元宵-都市霓虹",
    "title": "马年元宵 · 都市霓虹",
    "description": "AI 生成的真人风格短剧场景。2026年马年元宵节，现代都市街头，夜晚的霓虹灯与红色的元宵节灯笼交相辉映，展现传统节日与现代都市的融合。",
    "categoryId": "ai-live-drama",
    "type": "video",
    "file": "ai-live-drama/2026年马年元宵节，现代都市街头，夜晚的霓虹灯与红色的元宵节灯笼交相辉映.mp4",
    "thumbnail": "ai-live-drama/2026年马年元宵节，现代都市街头，夜晚的霓虹灯与红色的元宵节灯笼交相辉映.thumb.jpg",
    "tools": [
      "即梦AI",
      "剪映专业版"
    ],
    "tags": [
      "元宵节",
      "真人短剧",
      "都市",
      "节庆"
    ],
    "duration": "00:25",
    "createdAt": "2026-02",
    "featured": false
  },
  {
    "id": "无人机灯光秀-未来都市",
    "title": "无人机灯光秀 · 未来都市",
    "description": "AI 生成的真人风格短剧场景。2026年现代超级都市中心广场，夜空中数万架带冷光灯带的自律无人机集群表演，展现科技感十足的视觉盛宴。",
    "categoryId": "ai-live-drama",
    "type": "video",
    "file": "ai-live-drama/2026年现代超级都市中心广场，夜空中数万架带冷光灯带的自律无人机集群.mp4",
    "thumbnail": "ai-live-drama/2026年现代超级都市中心广场，夜空中数万架带冷光灯带的自律无人机集群.thumb.jpg",
    "tools": [
      "即梦AI",
      "ComfyUI",
      "剪映专业版"
    ],
    "tags": [
      "无人机",
      "科技",
      "都市",
      "灯光秀"
    ],
    "duration": "00:20",
    "createdAt": "2026-03",
    "featured": true
  },
  {
    "id": "汗血宝马-霓虹灯火",
    "title": "汗血宝马 · 霓虹灯火",
    "description": "AI 生成的真人风格短剧。2026马年限定款的汗血宝马造型艺术灯笼，霓虹灯火映照下的艺术造型。",
    "categoryId": "ai-live-drama",
    "type": "video",
    "file": "ai-live-drama/2026马年限定款的汗血宝马造型艺术灯笼。霓虹灯火.mp4",
    "thumbnail": "ai-live-drama/2026马年限定款的汗血宝马造型艺术灯笼。霓虹灯火.thumb.jpg",
    "tools": [
      "即梦AI",
      "剪映专业版"
    ],
    "tags": [
      "马年",
      "灯笼",
      "霓虹",
      "艺术造型"
    ],
    "duration": "00:15",
    "createdAt": "2026-06",
    "featured": false
  },
  {
    "id": "汗血宝马-概念预告",
    "title": "汗血宝马 · 概念预告",
    "description": "AI 制作的概念预告片，2026马年限定款的汗血宝马造型艺术灯笼，霓虹灯火下的艺术光影与动态呈现。",
    "categoryId": "ai-concept-trailer",
    "type": "video",
    "file": "ai-concept-trailer/2026马年限定款的汗血宝马造型艺术灯笼。霓虹灯火.mp4",
    "thumbnail": "ai-concept-trailer/2026马年限定款的汗血宝马造型艺术灯笼。霓虹灯火.thumb.jpg",
    "tools": [
      "即梦AI",
      "ComfyUI",
      "剪映专业版"
    ],
    "tags": [
      "概念预告",
      "马年",
      "艺术灯笼",
      "霓虹"
    ],
    "duration": "00:20",
    "createdAt": "2026-06",
    "featured": false
  },
  {
    "id": "创意短片-1",
    "title": "创意短片 1",
    "description": "AI 创意短视频作品，探索 AI 在视觉艺术与抽象叙事中的可能性。",
    "categoryId": "ai-creative-short",
    "type": "video",
    "file": "ai-creative-short/2026_______________________.mp4",
    "thumbnail": "ai-creative-short/2026_______________________.thumb.jpg",
    "tools": [
      "即梦AI"
    ],
    "tags": [
      "创意短片",
      "AI生成"
    ],
    "duration": "00:15",
    "createdAt": "2026-01",
    "featured": false
  },
  {
    "id": "创意短片-2",
    "title": "创意短片 2",
    "description": "AI 创意短视频作品，融合动态光影与叙事节奏的实验性短片。",
    "categoryId": "ai-creative-short",
    "type": "video",
    "file": "ai-creative-short/2026_______________________________.mp4",
    "thumbnail": "ai-creative-short/2026_______________________________.thumb.jpg",
    "tools": [
      "即梦AI",
      "剪映专业版"
    ],
    "tags": [
      "创意短片",
      "实验"
    ],
    "duration": "00:18",
    "createdAt": "2026-01",
    "featured": false
  },
  {
    "id": "创意短片-3",
    "title": "创意短片 3",
    "description": "AI 生成的创意短视频，探索抽象视觉风格与音乐节奏的融合。",
    "categoryId": "ai-creative-short",
    "type": "video",
    "file": "ai-creative-short/2026_________________________________.mp4",
    "thumbnail": "ai-creative-short/2026_________________________________.thumb.jpg",
    "tools": [
      "即梦AI",
      "Suno"
    ],
    "tags": [
      "创意短片",
      "音乐可视化"
    ],
    "duration": "00:20",
    "createdAt": "2026-02",
    "featured": false
  },
  {
    "id": "无人机灯光秀-创意版",
    "title": "无人机灯光秀 · 创意版",
    "description": "AI 创意短视频 — 无人机灯光秀的创意视觉呈现，探索 AI 在抽象技术与艺术表达间的融合。",
    "categoryId": "ai-creative-short",
    "type": "video",
    "file": "ai-creative-short/2026年现代超级都市中心广场，夜空中数万架带冷光灯带的自律无人机集群.mp4",
    "thumbnail": "ai-creative-short/2026年现代超级都市中心广场，夜空中数万架带冷光灯带的自律无人机集群.thumb.jpg",
    "tools": [
      "即梦AI"
    ],
    "tags": [
      "创意短片",
      "无人机",
      "灯光秀"
    ],
    "duration": "00:15",
    "createdAt": "2026-03",
    "featured": false
  },
  {
    "id": "元宵灯火-创意版",
    "title": "元宵灯火 · 创意版",
    "description": "AI 创意短视频 — 元宵节都市霓虹的创意抽象化呈现，用 AI 视角重新诠释传统节日色彩。",
    "categoryId": "ai-creative-short",
    "type": "video",
    "file": "ai-creative-short/2026年马年元宵节，现代都市街头，夜晚的霓虹灯与红色的元宵节灯笼交相辉映.mp4",
    "thumbnail": "ai-creative-short/2026年马年元宵节，现代都市街头，夜晚的霓虹灯与红色的元宵节灯笼交相辉映.thumb.jpg",
    "tools": [
      "即梦AI",
      "剪映专业版"
    ],
    "tags": [
      "创意短片",
      "元宵",
      "霓虹"
    ],
    "duration": "00:18",
    "createdAt": "2026-02",
    "featured": false
  },
  {
    "id": "汗血宝马-创意版",
    "title": "汗血宝马 · 创意版",
    "description": "AI 创意短视频 — 马年限定灯笼的创意视觉解读，霓虹灯火与艺术造型的动态融合。",
    "categoryId": "ai-creative-short",
    "type": "video",
    "file": "ai-creative-short/2026马年限定款的汗血宝马造型艺术灯笼。霓虹灯火.mp4",
    "thumbnail": "ai-creative-short/2026马年限定款的汗血宝马造型艺术灯笼。霓虹灯火.thumb.jpg",
    "tools": [
      "即梦AI",
      "ComfyUI"
    ],
    "tags": [
      "创意短片",
      "马年",
      "灯笼"
    ],
    "duration": "00:16",
    "createdAt": "2026-06",
    "featured": false
  },
  {
    "id": "现代ai艺术-100",
    "title": "现代AI艺术 · 100",
    "description": "AI 生成的现代视觉艺术作品，探索风格化图像创作的无限可能。",
    "categoryId": "ai-image-art",
    "type": "image",
    "file": "ai-image-art/100.png",
    "thumbnail": "ai-image-art/100.png",
    "tools": [
      "即梦AI"
    ],
    "tags": [
      "AI艺术",
      "现代风格"
    ],
    "duration": "",
    "createdAt": "2026-04-07",
    "featured": false
  },
  {
    "id": "角色手办转换",
    "title": "角色手办转换",
    "description": "将照片转换为角色手办的 AI 图像生成作品，展示 AI 在 3D 风格化转换中的创作能力。",
    "categoryId": "ai-image-art",
    "type": "image",
    "file": "ai-image-art/101 将这张照片转换为一个角色手办.png",
    "thumbnail": "ai-image-art/101 将这张照片转换为一个角色手办.png",
    "tools": [
      "即梦AI"
    ],
    "tags": [
      "手办",
      "角色设计",
      "3D风格"
    ],
    "duration": "",
    "createdAt": "2025-09-25",
    "featured": false
  },
  {
    "id": "现代ai艺术-102",
    "title": "现代AI艺术 · 102",
    "description": "AI 生成的视觉艺术作品，展现 AI 在图像创作中的独特美学风格。",
    "categoryId": "ai-image-art",
    "type": "image",
    "file": "ai-image-art/102.png",
    "thumbnail": "ai-image-art/102.png",
    "tools": [
      "即梦AI"
    ],
    "tags": [
      "AI艺术",
      "视觉创作"
    ],
    "duration": "",
    "createdAt": "2025-10-13",
    "featured": false
  },
  {
    "id": "圣诞节主题视觉海报",
    "title": "圣诞节主题视觉海报",
    "description": "2025年圣诞节主题视觉海报，核心画面以一颗由发光光纤和全息雪花构成的圣诞树为主体，融合科技感与节日氛围。",
    "categoryId": "ai-image-art",
    "type": "image",
    "file": "ai-image-art/103-圣诞节海报 核心画面： 2025年圣诞节主题视觉海报，以一颗由发光光纤和全息雪花....png",
    "thumbnail": "ai-image-art/103-圣诞节海报 核心画面： 2025年圣诞节主题视觉海报，以一颗由发光光纤和全息雪花....png",
    "tools": [
      "即梦AI"
    ],
    "tags": [
      "圣诞节",
      "海报设计",
      "全息",
      "科技感"
    ],
    "duration": "",
    "createdAt": "2025-12-08",
    "featured": true
  },
  {
    "id": "常山ai海报",
    "title": "常山AI海报",
    "description": "AI 生成的城市主题海报设计，以常山为灵感创作的视觉艺术作品。",
    "categoryId": "ai-image-art",
    "type": "image",
    "file": "ai-image-art/103常山AI海报.jpg",
    "thumbnail": "ai-image-art/103常山AI海报.jpg",
    "tools": [
      "即梦AI"
    ],
    "tags": [
      "海报",
      "城市",
      "AI设计"
    ],
    "duration": "",
    "createdAt": "2025-12",
    "featured": false
  },
  {
    "id": "现代ai艺术-104",
    "title": "现代AI艺术 · 104",
    "description": "AI 生成的视觉艺术作品，探索 AI 在图像构图与色彩搭配上的创作可能性。",
    "categoryId": "ai-image-art",
    "type": "image",
    "file": "ai-image-art/104.png",
    "thumbnail": "ai-image-art/104.png",
    "tools": [
      "即梦AI"
    ],
    "tags": [
      "AI艺术",
      "视觉创作"
    ],
    "duration": "",
    "createdAt": "2025-12-08",
    "featured": false
  },
  {
    "id": "现代ai艺术-200",
    "title": "现代AI艺术 · 200",
    "description": "AI 生成的视觉艺术作品，展现 AI 创作工具在艺术表达中的独特风格。",
    "categoryId": "ai-image-art",
    "type": "image",
    "file": "ai-image-art/200.png",
    "thumbnail": "ai-image-art/200.png",
    "tools": [
      "即梦AI"
    ],
    "tags": [
      "AI艺术",
      "现代风格"
    ],
    "duration": "",
    "createdAt": "2026-04-05",
    "featured": false
  },
  {
    "id": "现代ai艺术-201",
    "title": "现代AI艺术 · 201",
    "description": "AI 生成的视觉艺术作品，探索不同艺术风格在 AI 图像生成中的融合与创新。",
    "categoryId": "ai-image-art",
    "type": "image",
    "file": "ai-image-art/201.png",
    "thumbnail": "ai-image-art/201.png",
    "tools": [
      "即梦AI"
    ],
    "tags": [
      "AI艺术",
      "风格探索"
    ],
    "duration": "",
    "createdAt": "2025-09-25",
    "featured": false
  },
  {
    "id": "现代ai艺术-202",
    "title": "现代AI艺术 · 202",
    "description": "AI 生成的视觉艺术作品，展示 AI 在图像细节与质感表现上的创作能力。",
    "categoryId": "ai-image-art",
    "type": "image",
    "file": "ai-image-art/202.png",
    "thumbnail": "ai-image-art/202.png",
    "tools": [
      "即梦AI"
    ],
    "tags": [
      "AI艺术",
      "视觉创作"
    ],
    "duration": "",
    "createdAt": "2025-10-15",
    "featured": false
  }
];

export const WORK_CATEGORIES_META = [
  { id: 'ai-animation-drama', icon: '🎬' },
  { id: 'ai-live-drama', icon: '🎭' },
  { id: 'ai-concept-trailer', icon: '🎥' },
  { id: 'ai-creative-short', icon: '✨' },
  { id: 'ai-image-art', icon: '🖼️' },
];

export function getWorksByCategory(categoryId: string): WorkEntry[] {
  return WORKS_DATA.filter((w) => w.categoryId === categoryId);
}

export function getFeaturedWorks(): WorkEntry[] {
  return WORKS_DATA.filter((w) => w.featured);
}

export function getWorkById(id: string): WorkEntry | undefined {
  return WORKS_DATA.find((w) => w.id === id);
}
