// ═════════════════════════════════════════════════════════════
// Auto-generated by scripts/generate-works.mjs
// Do not edit manually — run `pnpm generate:works` to regenerate
// ═════════════════════════════════════════════════════════════

export interface WorkEntry {
  id: string;
  title: string;
  description: string;
  categoryId: string;
  type: 'video' | 'image';
  file: string;
  thumbnail: string;
  tools: string[];
  tags: string[];
  duration: string;
  createdAt: string;
  featured: boolean;
  bvid?: string;
}

export const WORKS_DATA: WorkEntry[] = [];

export const WORK_CATEGORIES_META = [
  { id: 'ai-animation-drama', icon: '\uD83C\uDFAC' },
  { id: 'ai-live-drama', icon: '\uD83C\uDFAD' },
  { id: 'ai-concept-trailer', icon: '\uD83C\uDFA5' },
  { id: 'ai-creative-short', icon: '\u2728' },
  { id: 'ai-image-art', icon: '\uD83D\uDDBC\uFE0F' },
];

export function getWorksByCategory(categoryId: string): WorkEntry[] {
  return WORKS_DATA.filter((w) => w.categoryId === categoryId);
}

export function getFeaturedWorks(): WorkEntry[] {
  return WORKS_DATA.filter((w) => w.featured);
}

export function getWorkById(id: string): WorkEntry | undefined {
  return WORKS_DATA.find((w) => w.id === id);
}